---
# Handler to handle squid3 notifications. Handlers are called by other plays.
# See http://docs.ansible.com/playbooks_intro.html for more information about handlers.

- name: restart squid3
  service: name=squid3 state=restarted
